### ISSUE TITLE
Unable to load library due to malformed DESCRIPTION meta-information

### ISSUE THREAD

**Issue by sharonml** [smmueller/plotdesignr#6]
The error message:

```
✓  checking for file ‘/private/var/folders/k2/9_1bl_yd4n93p87rr5lk1r7m0000gn/T/RtmpAEyzqU/remotes22b628b82ba1/smmueller-plotdesignr-4f6bb22/DESCRIPTION’ (470ms)
─  preparing ‘plotdesignr’:
E  checking DESCRIPTION meta-information ...
   Malformed maintainer field.
   
   See section 'The DESCRIPTION file' in the 'Writing R Extensions'
   manual.
   
Error: Failed to install 'plotdesignr' from GitHub:
  System command 'R' failed, exit status: 1, stdout + stderr:
E> * checking for file ‘/private/var/folders/k2/9_1bl_yd4n93p87rr5lk1r7m0000gn/T/RtmpAEyzqU/remotes22b628b82ba1/smmueller-plotdesignr-4f6bb22/DESCRIPTION’ ... OK
E> * preparing ‘plotdesignr’:
E> * checking  ... ERROR
E> Malformed maintainer field.
E> 
E> See section 'The DESCRIPTION file' in the 'Writing R Extensions'
E> manual.
E> 
```

**Comment by smmueller** [comment]
I think it should be fixed now (#7).

Just a note, this is a work in progress and there are very large known limitations about the way files are currently imported. Right now, only `.shp` files with coordinates in `lat lon` will work. I will make this more robust in the future based on other on-going projects, but I wanted to alert you to the current limitations.

**Comment by sharonml** [comment]
@smmueller thanks! Is the `lat lon` assumption just for `make_cluster_data` or is that assumed downstream in the actual clustering as well?

I was thinking of creating an `sf` object from each dataframe of points I have, but coordinates are in UTM.

**Comment by smmueller** [comment]
@sharonml  `lat lon` assumption impacts `make_cluster_data`. If you look at the example and create a data frame in the correct format yourself, instead of using the `make_cluster_data` function to do it for you, you should be able to move forward from there. `make_cluster_data` actually converts everything to UTM, but in an inflexible way. This is something I have marked to fix in the future. 

Closing this issue.
